//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrenregistratieClient.UrenregistratieService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrenregistratieService.IUrenregistratieservice")]
    public interface IUrenregistratieservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrenregistratieservice/Login", ReplyAction="http://tempuri.org/IUrenregistratieservice/LoginResponse")]
        bool Login(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrenregistratieservice/Login", ReplyAction="http://tempuri.org/IUrenregistratieservice/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string gebruikersnaam, string wachtwoord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrenregistratieserviceChannel : UrenregistratieClient.UrenregistratieService.IUrenregistratieservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrenregistratieserviceClient : System.ServiceModel.ClientBase<UrenregistratieClient.UrenregistratieService.IUrenregistratieservice>, UrenregistratieClient.UrenregistratieService.IUrenregistratieservice {
        
        public UrenregistratieserviceClient() {
        }
        
        public UrenregistratieserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrenregistratieserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrenregistratieserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrenregistratieserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string gebruikersnaam, string wachtwoord) {
            return base.Channel.Login(gebruikersnaam, wachtwoord);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string gebruikersnaam, string wachtwoord) {
            return base.Channel.LoginAsync(gebruikersnaam, wachtwoord);
        }
    }
}
